language: generic

services:
  - docker

env:
  matrix:
    - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.5.2
    - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.5.2
    - DISTRIBUTIONS=debian.stretch ANSIBLE_VERSION=2.5.2
    - DISTRIBUTIONS=centos.7       ANSIBLE_VERSION=2.5.2
    - DISTRIBUTIONS=ubuntu.xenial  ANSIBLE_VERSION=2.5.2

script:
  - make lint
  - make test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
